version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "test"]

# flags to specify which compose file I want to use.
# docker-compose -f docker-compose-dev.yml up
# docker-compose -f docker-compose-dev.yml up --build
# docker-compose -f docker-compose-dev.yml down